Repository googleinterns/pieced, pull requests merged in 2020-07, with the labels that each got.

#20 Java button
  src/main/java/com/google/sps/servlets/DataServlet.java
  src/main/java/com/google/sps/servlets/RefreshDataServlet.java
  src/main/java/com/google/sps/utils/data/DataCollection.java
  src/main/webapp/gallery.html
Labels: enhancement

#22 Nav bar
  src/main/webapp/gallery.html
  src/main/webapp/navigation.html
  src/main/webapp/scripts/gallery.js
  src/main/webapp/scripts/script.js
  src/main/webapp/scripts/species.js
  src/main/webapp/species.html
  src/main/webapp/styles/gallery.css
  src/main/webapp/styles/species.css
  src/main/webapp/styles/style.css
Labels: enhancement

#23 Gallery page
  CODEOWNERS
  src/main/webapp/gallery.html
  src/main/webapp/index.css
  src/main/webapp/index.html
  src/main/webapp/scripts/gallery.js
  src/main/webapp/species.html
  src/main/webapp/styles/gallery.css
Labels: requirement

#24 Fetch datastore
  pom.xml
  src/main/java/com/google/sps/servlets/DataServlet.java
  src/main/webapp/scripts/species.js
Labels: requirement

#27 Fix spacing issues with navbar
  src/main/webapp/gallery.html
  src/main/webapp/index.css
  src/main/webapp/index.html
  src/main/webapp/species.html
  src/main/webapp/styles/style.css
Labels: enhancement

#39 Add taxonomy to species data; feed all species data to gallery from backend
  src/main/java/com/google/sps/servlets/AllDataServlet.java
  src/main/java/com/google/sps/servlets/SpeciesDataServlet.java
  src/main/webapp/scripts/fetchData.js
  src/main/webapp/scripts/gallery.js
  src/main/webapp/species.html
Labels: cla: yes, requirement

#18 Milestone 1
  .gitignore
  pom.xml
  src/main/java/com/google/sps/servlets/AllDataServlet.java
  src/main/java/com/google/sps/servlets/DataServlet.java
  src/main/java/com/google/sps/servlets/RefreshDataServlet.java
  src/main/java/com/google/sps/servlets/SpeciesDataServlet.java
  src/main/java/com/google/sps/utils/data/DataCollection.java
  src/main/java/com/google/sps/utils/data/PopulationTrend.java
  src/main/java/com/google/sps/utils/data/Scraping.java
  src/main/java/com/google/sps/utils/data/Species.java
  src/main/java/com/google/sps/utils/data/SpeciesAPIRetrieval.java
  src/main/java/com/google/sps/utils/data/TaxonomicPath.java
  src/main/java/com/google/sps/utils/data/animals-test.json
  src/main/java/com/google/sps/utils/pixelation/Pixel.java
  src/main/webapp/gallery.html
  src/main/webapp/index.html
  src/main/webapp/navigation.html
  src/main/webapp/script.js
  src/main/webapp/scripts/fetchData.js
  src/main/webapp/scripts/gallery.js
  src/main/webapp/scripts/pixelation.js
  src/main/webapp/scripts/script.js
  src/main/webapp/species.html
  src/main/webapp/style.css
  src/main/webapp/styles/gallery.css
  src/main/webapp/styles/species.css
  src/main/webapp/styles/style.css
Labels: cla: yes, requirement

#41 Filter
  src/main/java/com/google/sps/servlets/AllDataServlet.java
  src/main/webapp/gallery.html
  src/main/webapp/index.html
  src/main/webapp/navigation.html
  src/main/webapp/scripts/gallery.js
  src/main/webapp/scripts/script.js
  src/main/webapp/styles/gallery.css
  src/main/webapp/styles/style.css
Labels: cla: yes, requirement

#42 Get largest image available
  src/main/java/com/google/sps/utils/data/DataCollection.java
Labels: cla: yes, enhancement

#46 Cleaned up Datastore attributes
  src/main/java/com/google/sps/servlets/SpeciesDataServlet.java
  src/main/java/com/google/sps/utils/data/DataCollection.java
  src/main/java/com/google/sps/utils/data/Species.java
  src/main/webapp/scripts/fetchData.js
  src/main/webapp/species-template.html
  src/main/webapp/styles/species.css
Labels: cla: yes

#49 Added homepage blurb and updated species page formatting
  src/main/java/com/google/sps/utils/data/DataCollection.java
  src/main/webapp/index.html
  src/main/webapp/species-template.html
  src/main/webapp/styles/index.css
  src/main/webapp/styles/species.css
Labels: cla: yes

#51 Revert "Filter"
  src/main/java/com/google/sps/servlets/AllDataServlet.java
  src/main/java/com/google/sps/servlets/SpeciesDataServlet.java
  src/main/java/com/google/sps/utils/data/DataCollection.java
  src/main/java/com/google/sps/utils/data/Species.java
  src/main/webapp/gallery.html
  src/main/webapp/index.html
  src/main/webapp/navigation.html
  src/main/webapp/scripts/fetchData.js
  src/main/webapp/scripts/gallery.js
  src/main/webapp/scripts/script.js
  src/main/webapp/scripts/species-template.js
  src/main/webapp/species-template.html
  src/main/webapp/species.html
  src/main/webapp/styles/gallery.css
  src/main/webapp/styles/species.css
  src/main/webapp/styles/style.css
Labels: cla: yes

#58 Species layout
  src/main/webapp/species-template.html
  src/main/webapp/styles/species.css
Labels: cla: yes

#57 Geo
  src/main/java/com/google/sps/servlets/AllDataServlet.java
  src/main/java/com/google/sps/servlets/SpeciesDataServlet.java
  src/main/java/com/google/sps/utils/data/DataCollection.java
  src/main/java/com/google/sps/utils/data/Species.java
  src/main/java/com/google/sps/utils/data/SpeciesAPIRetrieval.java
  src/main/webapp/index.html
  src/main/webapp/scripts/geo.js
  src/main/webapp/species-template.html
  src/main/webapp/species.html
  src/main/webapp/styles/maps.css
  src/main/webapp/styles/species.css
  src/main/webapp/styles/style.css
Labels: cla: yes

#69 Add data
  .gitignore
  pom.xml
  src/main/java/com/google/sps/utils/data/DataCollection.java
  src/main/java/com/google/sps/utils/data/Species.java
  src/main/java/com/google/sps/utils/data/SpeciesAPIRetrieval.java
Labels: cla: yes

#66 Pixel math
  src/main/webapp/index.html
  src/main/webapp/scripts/fetchData.js
  src/main/webapp/scripts/pixelation.js
  src/main/webapp/scripts/species-template.js
  src/main/webapp/species-template.html
  src/main/webapp/species.html
  src/main/webapp/styles/species.css
Labels: cla: yes

#70 Filter, Search, Sort
  src/main/java/com/google/sps/servlets/AllDataServlet.java
  src/main/webapp/gallery.html
  src/main/webapp/scripts/gallery.js
  src/main/webapp/styles/gallery.css
Labels: cla: yes, requirement

#71 About page
  src/main/webapp/index.html
Labels: cla: yes

#72 Fix bug with layouts where it'd all become one column
  src/main/webapp/gallery.html
  src/main/webapp/scripts/gallery.js
Labels: bug, cla: yes

#73 Add data
  src/main/java/com/google/sps/utils/data/DataCollection.java
  src/main/java/com/google/sps/utils/data/SpeciesAPIRetrieval.java
  src/main/webapp/gallery.html
Labels: cla: yes

#74 Action page
  src/main/webapp/action.html
  src/main/webapp/navigation.html
  src/main/webapp/styles/action.css
Labels: cla: yes

#77 Greyed out extinct animals
  src/main/webapp/gallery.html
  src/main/webapp/scripts/gallery.js
  src/main/webapp/styles/gallery.css
Labels: cla: yes

#80 Fixed action page
  src/main/webapp/action.html
  src/main/webapp/styles/action.css
Labels: cla: yes

#82 Fix all merge conflicts
  src/main/java/com/google/sps/servlets/AllDataServlet.java
  src/main/java/com/google/sps/servlets/RefreshDataServlet.java
  src/main/java/com/google/sps/servlets/SpeciesDataServlet.java
  src/main/java/com/google/sps/utils/data/DataCollection.java
  src/main/java/com/google/sps/utils/data/Species.java
  src/main/java/com/google/sps/utils/data/SpeciesAPIRetrieval.java
  src/main/java/com/google/sps/utils/data/animals-test.json
  src/main/webapp/scripts/fetchData.js
  src/main/webapp/scripts/gallery.js
  src/main/webapp/scripts/pixelation.js
  src/main/webapp/scripts/script.js
  src/main/webapp/styles/gallery.css
  src/main/webapp/styles/species.css
  src/main/webapp/styles/style.css
Labels: cla: yes

#83 Filter
  src/main/java/com/google/sps/servlets/AllDataServlet.java
  src/main/webapp/gallery.html
  src/main/webapp/scripts/gallery.js
Labels: cla: yes, enhancement

#84 Add minor changes to README
  README.md
Labels: cla: yes, enhancement

#85 Add population reset button
  src/main/webapp/scripts/pixelation.js
  src/main/webapp/species-template.html
  src/main/webapp/styles/species.css
Labels: cla: yes

#75 revert rectangular images to prevent graphical glitch
  src/main/webapp/scripts/fetchData.js
  src/main/webapp/species-template.html
Labels: cla: yes
